const equipmentCategories = [
  {
    slug: 'refrigeration',
    label: 'Refrigeration',
    items: [
      'Walk-In Coolers',
      'Walk-In Freezers',
      'Reach-In Refrigerators',
      'Reach-In Freezers',
      'Undercounter Refrigerators',
      'Undercounter Freezers',
      'Display Cases & Merchandisers',
      'Bar Coolers',
      'Beverage Coolers',
      'Milk Coolers',
      'Refrigerated Prep Tables',
      'Blast Chillers',
    ],
  },
  {
    slug: 'hvac',
    label: 'HVAC & AC',
    items: [
      'Rooftop Package Units (RTUs)',
      'Split Systems',
      'Mini-Split Systems',
      'Ductless Systems',
      'Package Units',
      'Make-Up Air Units',
      'Condensing Units',
      'Thermostats & Building Controls',
      'Ductwork & Airflow Systems',
    ],
  },
  {
    slug: 'ice-machines',
    label: 'Ice Machines',
    items: ['Cube Ice Machines', 'Flake Ice Machines', 'Nugget Ice Machines', 'Undercounter Ice Makers', 'Ice Storage Bins', 'Water Filtration Systems'],
  },
  {
    slug: 'kitchen-equipment',
    label: 'Kitchen Equipment',
    items: [
      'Ranges (Gas & Electric)',
      'Convection Ovens',
      'Combi Ovens',
      'Deck Ovens',
      'Conveyor Ovens',
      'Fryers (Gas & Electric)',
      'Griddles',
      'Charbroilers',
      'Steamers',
      'Braising Pans',
      'Holding Cabinets & Warmers',
      'Commercial Dishwashers',
      'Conveyor Dish Machines',
      'Undercounter Warewashers',
      'Prep Tables',
      'Slicers',
      'Food Processors',
      'Meat Grinders',
    ],
  },
  {
    slug: 'mixers',
    label: 'Mixers',
    items: ['Stand Mixers', 'Spiral Mixers', 'Planetary Mixers', 'Bowl-Lift Mixers', 'Bench Mixers'],
  },
  {
    slug: 'exhaust-hoods',
    label: 'Exhaust Hoods',
    items: ['Type I Grease Hoods', 'Type II Condensate Hoods', 'Exhaust Fans', 'Make-Up Air Fans', 'Ductwork & Airflow Systems', 'Control Switches & Wiring'],
  },
];

module.exports = { equipmentCategories };
