const services = [
  {
    slug: 'commercial-refrigeration-repair',
    serviceName: 'Commercial Refrigeration Repair',
    icon: '🧊',
    cardTitle: 'Commercial Refrigeration Repair',
    cardBlurb: 'Walk-in coolers & freezers, reach-ins, display cases — from temperature drift to full system failure.',
    pageTitle: 'Commercial Refrigeration Repair in Miami | Walk-In Coolers & Freezers | ProFix305',
    metaDescription: 'Commercial refrigeration repair across Miami-Dade, Broward, and Palm Beach. Walk-in coolers & freezers, reach-in units, display cases. Insured techs, same-day dispatch, flat-rate pricing.',
    keywords: 'commercial refrigeration repair Miami, walk-in cooler repair, walk-in freezer repair, reach-in cooler repair, display case repair Miami',
    heroEyebrow: 'Commercial Refrigeration',
    heroHeadline: 'Commercial Refrigeration Repair, Same Day',
    heroSub: 'Miami’s summers don’t give refrigeration equipment any margin for error. Whether it’s a walk-in cooler holding your entire week’s inventory or a reach-in case on your sales floor, ProFix305 technicians diagnose and repair the full range of commercial refrigeration systems across South Florida.',
    bullets: [
      'Walk-in cooler & freezer repair — from minor temperature drift to full compressor failure',
      'Reach-in refrigerator & freezer repair for kitchens and retail floors',
      'Display case & merchandiser refrigeration repair',
      'Compressor diagnostics, sourcing, and replacement',
      'Evaporator & condenser coil cleaning and replacement',
      'Door, gasket, hinge, and door-heater repair',
      'Digital thermostat and controller calibration',
      'Refrigerant leak detection and recharge',
    ],
    faqs: [
      {
        q: 'How fast can you repair a walk-in cooler or freezer in Miami?',
        a: 'Most refrigeration calls across Miami-Dade, Broward, and Palm Beach are dispatched the same day, with active breakdowns (units at risk of a total inventory loss) prioritized first.',
      },
      {
        q: 'Do you work on reach-in units as well as walk-ins?',
        a: 'Yes — our technicians service walk-in coolers and freezers, reach-in refrigerators, and display/merchandiser cases across all major commercial brands.',
      },
      {
        q: 'What usually causes a walk-in cooler to stop cooling?',
        a: 'The most common causes are compressor failure, a refrigerant leak, a failed evaporator or condenser fan, or a door seal that’s let in warm air faster than the system can compensate. We diagnose the root cause before quoting a repair.',
      },
    ],
  },
  {
    slug: 'commercial-hvac-ac-repair',
    serviceName: 'Commercial HVAC & AC Repair',
    icon: '🌡️',
    cardTitle: 'HVAC & Air Conditioning Repair',
    cardBlurb: 'Commercial AC and rooftop units serviced and repaired to keep your space comfortable and code-compliant.',
    pageTitle: 'Commercial HVAC & AC Repair in Miami | ProFix305',
    metaDescription: 'Commercial HVAC and air conditioning repair for restaurants, retail, and offices across Miami-Dade, Broward, and Palm Beach County. Rooftop units, split systems, same-day emergency service.',
    keywords: 'commercial HVAC repair Miami, commercial AC repair, rooftop unit repair, commercial air conditioning service South Florida',
    heroEyebrow: 'Commercial HVAC',
    heroHeadline: 'Commercial HVAC & AC Repair That Doesn’t Wait',
    heroSub: 'A dead AC unit in a South Florida summer isn’t just uncomfortable — it can shut down a dining room or send staff home. ProFix305 repairs commercial HVAC and air conditioning systems for restaurants, retail spaces, offices, and warehouses across South Florida.',
    bullets: [
      'Rooftop package unit (RTU) repair and service',
      'Split-system and mini-split commercial AC repair',
      'Compressor, capacitor, and fan motor replacement',
      'Refrigerant leak detection, recharge, and recovery',
      'Thermostat and building control diagnostics',
      'Airflow, ductwork, and drainage issue troubleshooting',
      'Seasonal tune-ups ahead of peak summer load',
      'Preventive maintenance plans to reduce breakdown risk',
    ],
    faqs: [
      {
        q: 'Do you repair rooftop commercial AC units?',
        a: 'Yes — we service rooftop package units (RTUs), split systems, and mini-splits used in restaurants, retail, and office spaces across Miami-Dade, Broward, and Palm Beach.',
      },
      {
        q: 'Can you come out the same day if our AC goes down?',
        a: 'In most cases, yes. Emergency HVAC calls are prioritized for same-day dispatch, since a down AC system in South Florida heat affects both staff and customers quickly.',
      },
      {
        q: 'Do you offer HVAC maintenance plans, not just repairs?',
        a: 'Yes, scheduled tune-ups and inspections catch worn capacitors, low refrigerant, and airflow issues before they cause a full breakdown — especially valuable heading into summer.',
      },
    ],
  },
  {
    slug: 'commercial-ice-machine-repair',
    serviceName: 'Commercial Ice Machine Repair',
    icon: '❄️',
    cardTitle: 'Ice Machine Repair & Maintenance',
    cardBlurb: 'Slow production, cloudy ice, or a machine that’s stopped entirely — we get it back to full output.',
    pageTitle: 'Commercial Ice Machine Repair in Miami | Ice Makers | ProFix305',
    metaDescription: 'Commercial ice machine and ice maker repair across Miami-Dade, Broward, and Palm Beach. Low production, cloudy or off-taste ice, water leaks, and full breakdowns — same-day dispatch.',
    keywords: 'commercial ice machine repair Miami, ice maker repair, ice machine service South Florida, restaurant ice machine repair',
    heroEyebrow: 'Ice Machines',
    heroHeadline: 'Commercial Ice Machine Repair & Maintenance',
    heroSub: 'A slow or broken ice machine hits bars, restaurants, and hotels fast — especially during a Miami rush. ProFix305 diagnoses and repairs commercial ice machines and ice makers across South Florida, from production slowdowns to full breakdowns.',
    bullets: [
      'Low or no ice production diagnostics and repair',
      'Cloudy, off-taste, or undersized ice cube troubleshooting',
      'Water inlet valve, pump, and line repair',
      'Condenser cleaning for units running hot or short-cycling',
      'Bin control and thermostat calibration',
      'Descaling and sanitation service to protect ice quality',
      'Full-unit replacement guidance when a repair no longer makes sense',
      'Scheduled maintenance plans to prevent slowdowns before a rush',
    ],
    faqs: [
      {
        q: 'Our ice machine is making ice slower than usual — is that worth a service call?',
        a: 'Yes. Slow production is often an early sign of a dirty condenser, scale buildup, or a failing water valve — catching it early is cheaper than waiting for a full stoppage.',
      },
      {
        q: 'Do you service both under-counter and standalone ice machines?',
        a: 'Yes, our technicians work on under-counter units, standalone ice makers, and larger production machines used in restaurants, bars, hotels, and grocery operations.',
      },
      {
        q: 'Can cloudy ice mean something is wrong with the machine?',
        a: 'Often yes — cloudy or soft ice can point to mineral buildup, a water filtration issue, or a refrigerant problem. We diagnose the cause rather than just resetting the unit.',
      },
    ],
  },
  {
    slug: 'commercial-kitchen-equipment-repair',
    serviceName: 'Commercial Kitchen Equipment Repair',
    icon: '🔥',
    cardTitle: 'Commercial Kitchen Equipment Repair',
    cardBlurb: 'Ranges, ovens, fryers, griddles, and dishwashers — keeping your line moving during service.',
    pageTitle: 'Commercial Kitchen Equipment Repair in Miami | Ranges, Ovens, Fryers | ProFix305',
    metaDescription: 'Commercial kitchen equipment repair for restaurants and hotels across Miami-Dade, Broward, and Palm Beach. Ranges, ovens, fryers, griddles, dishwashers. Insured techs, flat-rate pricing.',
    keywords: 'commercial kitchen equipment repair Miami, commercial oven repair, fryer repair, griddle repair, restaurant equipment repair South Florida',
    heroEyebrow: 'Kitchen Equipment',
    heroHeadline: 'Commercial Kitchen Equipment Repair',
    heroSub: 'A down range, fryer, or dishwasher during service is a lost ticket every minute it sits broken. ProFix305 repairs the equipment your kitchen line depends on, across restaurants, hotels, and institutional kitchens in South Florida.',
    bullets: [
      'Range, oven, and griddle repair',
      'Fryer repair, including gas and electric units',
      'Commercial dishwasher and warewasher repair',
      'Steam table and holding equipment repair',
      'Gas line and burner diagnostics',
      'Electrical and control panel troubleshooting',
      'Preventive maintenance to reduce mid-service breakdowns',
      'Health-code-relevant repairs handled with inspection standards in mind',
    ],
    faqs: [
      {
        q: 'Can you repair equipment during business hours without shutting down the kitchen?',
        a: 'In most cases yes — our technicians work around service hours where possible and prioritize getting critical line equipment back online fast.',
      },
      {
        q: 'Do you work on both gas and electric kitchen equipment?',
        a: 'Yes, our technicians are equipped to diagnose and repair both gas and electric ranges, ovens, fryers, and related kitchen equipment.',
      },
      {
        q: 'What kitchen equipment brands do you service?',
        a: 'We service all major commercial kitchen equipment brands used in South Florida restaurants and hotels — ask our dispatch team if you have a specific brand question.',
      },
    ],
  },
  {
    slug: 'commercial-mixer-repair',
    serviceName: 'Commercial Mixer Repair',
    icon: '🥣',
    cardTitle: 'Commercial Mixer Repair',
    cardBlurb: 'Stand mixers and spiral mixers repaired — gearbox, motor, and bowl-lift issues fixed on-site.',
    pageTitle: 'Commercial Mixer Repair in Miami | Bakery & Restaurant Mixers | ProFix305',
    metaDescription: 'Commercial mixer repair for bakeries, restaurants, and pizzerias across Miami-Dade, Broward, and Palm Beach. Gearbox, motor, bowl-lift, and speed control repairs.',
    keywords: 'commercial mixer repair Miami, bakery mixer repair, spiral mixer repair, stand mixer repair South Florida',
    heroEyebrow: 'Commercial Mixers',
    heroHeadline: 'Commercial Mixer Repair for Bakeries & Kitchens',
    heroSub: 'A broken mixer stalls dough, batter, and prep production fast. ProFix305 repairs commercial stand mixers and spiral mixers for bakeries, pizzerias, and restaurant kitchens across South Florida.',
    bullets: [
      'Gearbox and transmission repair',
      'Motor diagnostics and replacement',
      'Bowl-lift mechanism repair',
      'Speed control and switch repair',
      'Attachment hub and drive repair',
      'Noise, vibration, and overheating diagnostics',
      'Preventive maintenance for high-use bakery and kitchen mixers',
    ],
    faqs: [
      {
        q: 'Do you repair both stand mixers and spiral mixers?',
        a: 'Yes, our technicians service stand mixers and spiral mixers used in bakeries, pizzerias, and commercial kitchens.',
      },
      {
        q: 'My mixer is making a grinding noise — is that a gearbox issue?',
        a: 'Grinding or whining noises are commonly a gearbox or bearing issue. We diagnose on-site before recommending a repair versus replacement.',
      },
      {
        q: 'Can a mixer repair usually be done same day?',
        a: 'Many mixer repairs can be diagnosed and completed same day depending on parts availability — our dispatch team will give you a clear timeline when you book.',
      },
    ],
  },
  {
    slug: 'commercial-exhaust-hood-repair',
    serviceName: 'Commercial Exhaust Hood Repair',
    icon: '🏭',
    cardTitle: 'Exhaust Hood Repair & Service',
    cardBlurb: 'Kitchen exhaust hood, fan, and ventilation repair to keep your line compliant and running.',
    pageTitle: 'Commercial Exhaust Hood Repair in Miami | Kitchen Ventilation | ProFix305',
    metaDescription: 'Commercial kitchen exhaust hood and ventilation repair across Miami-Dade, Broward, and Palm Beach. Fan motor, ductwork, and fire-suppression-adjacent repairs. Same-day dispatch.',
    keywords: 'commercial exhaust hood repair Miami, kitchen exhaust fan repair, restaurant hood ventilation repair South Florida',
    heroEyebrow: 'Exhaust Hoods',
    heroHeadline: 'Commercial Exhaust Hood & Ventilation Repair',
    heroSub: 'A malfunctioning exhaust hood isn’t just uncomfortable for kitchen staff — it can be a health-inspection and fire-code issue. ProFix305 repairs commercial kitchen exhaust hoods and ventilation systems across South Florida.',
    bullets: [
      'Exhaust fan motor diagnostics and replacement',
      'Hood ductwork and airflow troubleshooting',
      'Belt, bearing, and pulley repair',
      'Control switch and wiring repair',
      'Grease buildup and airflow restriction diagnostics',
      'Inspection-readiness checks ahead of health or fire code visits',
      'Preventive maintenance plans for high-volume kitchens',
    ],
    faqs: [
      {
        q: 'Can a broken exhaust hood affect my health inspection?',
        a: 'Yes — inspectors check that ventilation is functioning properly. We can prioritize repairs ahead of a scheduled inspection when you let us know.',
      },
      {
        q: 'Do you repair the exhaust fan motor itself, or just the hood?',
        a: 'Both — we diagnose and repair exhaust fan motors, ductwork, airflow issues, and the hood’s control and wiring components.',
      },
      {
        q: 'How do I know if my exhaust hood needs a repair versus a cleaning?',
        a: 'If airflow is weak, the fan is loud or not running, or smoke/heat is lingering in the kitchen despite regular cleaning, that points to a mechanical issue rather than a grease buildup — worth a diagnostic visit.',
      },
    ],
  },
  {
    slug: 'commercial-equipment-cleaning-maintenance',
    serviceName: 'Equipment Cleaning & Preventive Maintenance',
    icon: '✨',
    cardTitle: 'Cleaning & Preventive Maintenance',
    cardBlurb: 'Ice machine sanitation, coil & condenser cleaning, scheduled maintenance plans — stop breakdowns before they happen.',
    pageTitle: 'Commercial Equipment Cleaning & Preventive Maintenance in Miami | ProFix305',
    metaDescription: 'Commercial kitchen equipment cleaning and preventive maintenance across Miami-Dade, Broward, and Palm Beach. Ice machine cleaning & sanitation, refrigeration coil cleaning, condenser cleaning, scheduled maintenance plans for restaurants and food service.',
    keywords: 'ice machine cleaning Miami, commercial refrigeration coil cleaning, condenser cleaning service, restaurant equipment cleaning Miami, preventive maintenance commercial kitchen, ice machine sanitation service',
    heroEyebrow: 'Cleaning & Maintenance',
    heroHeadline: 'Equipment Cleaning & Preventive Maintenance',
    heroSub: 'Most emergency breakdowns we see started as a dirty condenser coil, a scaled-up ice machine, or a clogged drain line that nobody touched for a year. Regular professional cleaning keeps equipment efficient, extends its life, keeps health inspectors happy — and costs a fraction of an emergency repair. ProFix305 offers one-time deep cleaning and scheduled maintenance plans across South Florida.',
    bullets: [
      'Ice machine deep cleaning, descaling & sanitation — health-code critical and often overlooked',
      'Refrigeration condenser & evaporator coil cleaning — dirty coils are the #1 cause of compressor failure',
      'Walk-in cooler/freezer drain line clearing and gasket care',
      'HVAC coil and blower cleaning for better airflow and lower power bills',
      'Kitchen equipment maintenance — burners, pilots, calibration, lubrication',
      'Scheduled preventive-maintenance plans (monthly / quarterly) with documented service records',
      'Pre-inspection tune-ups before health or fire inspections',
    ],
    faqs: [
      {
        q: 'How often should a commercial ice machine be cleaned in Florida?',
        a: 'Manufacturers and health codes generally call for a full cleaning and sanitation at least every 6 months — and in South Florida\'s climate, high-volume machines often need it quarterly. Scale and slime buildup is one of the most common health-inspection violations for bars and restaurants.',
      },
      {
        q: 'Why does condenser coil cleaning matter?',
        a: 'A dirty condenser makes the compressor run hotter and longer for the same cooling — raising power bills, shortening compressor life, and eventually causing the exact emergency breakdown that costs 10x more than a cleaning. It\'s the single highest-value maintenance task for refrigeration equipment.',
      },
      {
        q: 'Do you offer recurring maintenance plans?',
        a: 'Yes — we set up monthly or quarterly preventive-maintenance visits tailored to your equipment list, with documented service records you can show inspectors, insurers, and landlords. Plan customers also get priority dispatch on emergency calls.',
      },
      {
        q: 'Is exhaust hood cleaning included?',
        a: 'We service and repair exhaust hood systems (fans, belts, airflow issues) and can help you stay on your fire-code cleaning schedule. For certified NFPA 96 grease-duct deep cleaning we\'ll point you to a certified specialist if your inspection requires one — and handle everything mechanical around it.',
      },
    ],
  },
];

module.exports = { services };
